spring:
  application:
    name: waaData
  datasource:
    password: 1
    url: jdbc:postgresql://localhost:5432/waaData
    username: postgres
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
    show-sql: true
    defer-datasource-initialization: true
    generate-ddl: true
  sql:
     init:
      mode: always
  main:
    allow-circular-references: true
server:
  port: 8080
